#!/usr/bin/make -f
# Use bash to support “source” if needed
SHELL := /bin/bash

SKEL = config/includes.chroot/etc/skel
VIMRC_REPO = https://github.com/radiaku/vimrc.git
VIMRC_SRC = build/vimrc_src

all: clean prepare fetch_vimrc install_vimrc build_iso

prepare:
	mkdir -p $(SKEL)/.config/i3
	mkdir -p config/includes.chroot/etc/systemd/system

fetch_vimrc:
	@echo ">>> Cloning vimrc repo..."
	rm -rf $(VIMRC_SRC)
	mkdir -p build
	git clone $(VIMRC_REPO) $(VIMRC_SRC)

install_vimrc:
	@echo ">>> Installing vimrc into skel..."
	rm -rf $(SKEL)/.vimrc_runtime
	cp -r $(VIMRC_SRC) $(SKEL)/.vimrc_runtime
	@echo ">>> Writing .vimrc"
	cat << 'EOF' > $(SKEL)/.vimrc
" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vimrc_runtime/my_configs.vim

set runtimepath+=~/.vimrc_runtime

let data_dir = expand('~/.vimrc_runtime')

source ~/.vimrc_runtime/vimrcs/default_config.vim

if !empty(glob(data_dir . '/plugged/*'))
  source ~/.vimrc_runtime/vimrcs/basic.vim
  source ~/.vimrc_runtime/vimrcs/extended.vim
  source ~/.vimrc_runtime/vimrcs/plugin_config.vim
endif
EOF

build_iso:
	# Clean previous LB build state
	sudo lb clean --all

	# Configure LB
	sudo lb config --debug --distribution bookworm \
	  --memtest memtest86+ \
	  --bootappend-live "boot=live component username=radia" \
	  --debian-installer live \
	  --backports true \
	  --archive-areas "main contrib non-free non-free-firmware" \
	  --hdd-label RADIA-bookworm \
	  --uefi-secure-boot disable \
	  --image-name RADIA-bookworm \
	  --linux-packages "linux-image linux-headers"

	# Installer settings
	echo "debian-installer-launcher" > config/package-lists/installer.list.chroot
	echo "d-i debian-installer/locale string en_US" > config/includes.installer/preseed.cfg

	# Copy package list for desktop
	cat packages.list > config/package-lists/desktop.list.chroot

	# Copy other configs: bashrc, i3config, wallpaper, etc.
	cp .bashrc $(SKEL)/.bashrc
	cp i3config $(SKEL)/.config/i3/config
	cp kraut.png $(SKEL)/.config/i3/
	cp forest_refuge.vim $(SKEL)/.vimrc_runtime # if you want as a color scheme

	echo "exec --no-startup-id feh --bg-scale /home/radia/.config/i3/kraut.png" \
	  >> $(SKEL)/.config/i3/config

	# Bootloader customization
	cp -r /usr/share/live/build/bootloaders config/
	cp My_cephei_pxi.png config/bootloaders/grub-pc/splash.png

	# Finally build the ISO
	sudo lb build 2>&1 | tee build.log

clean:
	sudo lb clean || true
	rm -rf $(SKEL)/.vimrc $(SKEL)/.vimrc_runtime
	rm -rf build
